variable "vpc_cidr" {}
variable "env" {}
variable "public_subent" {}
variable "private_subent" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "account_no" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}