variable "component" {}
variable "env" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "app_port" {}
variable "subnets" {}
variable "vpc_cidr" {}
variable "bastion_node_cidr" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}